export const categoriesList = [
    {
        name: 'Automotriz',
        subcategories: [
            'Motocicletas',
            'Audio y video para automóviles',
            'Cuidado de interior del auto',
            'Luces y accesorios de iluminación',
            'Herramientas y equipo',
            'Soporte de teléfono para auto',
            'Piezas y accesorios para RV',
            'Neumáticos y ruedas',
            'Muebles para caravanas',
            'Cuidado exterior del auto',
            'Herramientas manuales',
            'Accesorios de exteriores',
            'Almacenamiento y organizadores de auto',
            'Parasoles para coche',
            'Llaveros y fundas de llave',
            'Accesorios de interior',
            'Piezas de repuesto',
            'Cobertores, tapetes y cojines',
            'Pegatinas de coche',
        ],
    },
    {
        name: 'Bebé y maternidad',
        subcategories: [
            'Seguridad',
            'Entrenamiento para dejar el pañal',
            'Cuidado del bebé',
            'Entretenimiento para bebé',
            'Equipo de viaje para bebés',
            'Productos personalizados',
            'Embarazo y maternidad',
            'Cambio de pañales',
            'Juguetes para bebés y niños',
            'Alimentación',
            'Almacenamiento y organización para bebés',
            'Carriolas y otros',
            'Regalos para bebés',
            'Guardería',
            'Papelería de bebé',
            'Decoración de guardería',
        ],
    },
    {
        name: 'Belleza y salud',
        subcategories: [
            'Afeitado y depilación',
            'Cuidado bucal',
            'Maquillaje',
            'Cuidado del cabello',
            'Accesorios de baño',
            'Corte de cabello',
            'Herramientas de belleza',
            'Equipo de salón y masaje',
            'Cuidado de pies, manos y uñas',
            'Polvo de uñas',
            'Cuidado de la piel',
            'Esmalte de uñas',
            'Maquillaje corporal',
            'Contenedores recargables',
            'Pestañas postizas',
            'Cuidado facial',
            'Cuidado personal',
            'Accesorios para peinar el cabello',
            'Espejo para maquillarse',
            'Decoración de uñas',
            'Bolsas de maquillaje y almacenamiento',
            'Perfumes',
            'Pelucas y accesorios',
            'Tatuajes temporales',
            'Uñas postizas presionadas',
        ],
    },
    {
        name: 'Bolsas y equipaje',
        subcategories: [
            'Maletines',
            'Mochilas de senderismo',
            'Mochilas para el día',
            'Bolsos para computadoras portátiles',
            'Bolsos de cintura y pecho',
            'Productos personalizados',
            'Bolsos de hombro para hombre',
            'Fundas de pasaporte y carteras',
            'Paraguas',
            'Mochilas para estudiantes',
            'Bolsos de mano para hombre',
            'Mochilas y bolsos de libros para mujer',
            'Billeteras y tarjeteros para hombre',
            'Bolsos cruzados para mujer',
            'Bolsas de mujer',
            'Riñoneras y bolsos de cintura para mujer',
            'Bolsas de almacenamiento',
            'Equipaje de viaje',
            'Bolsos de hombro para mujer',
            'Billeteras y tarjeteros para mujer',
            'Set de bolsos para mujer',
            'Bolsos de mano y de noche para mujer',
            'Neceser y bolsas de aseo',
            'Bolsas de mensajero',
            'Accesorios para maletas y bolsos de viaje',
            'Bolsos para mujer',
            'Bolsos Hobo',
            'Bolso de gimnasio',
            'Bolsos de mano para mujer',
            'Bolsas de maquillaje',
            'Bolsos de lona',
            'maleta',
        ],
    },
    {
        name: 'Calzado de hombre',
        subcategories: [
            'Pantuflas para hombre',
            'Calzado de patinar para hombre',
            'Calzado de trabajo y seguridad para hombre',
            'Calzado casual para hombre',
            'Sandalias para hombre',
            'Calzado de lona para hombre',
            'Mocasines y sandalias sin cordones para hombre',
            'Botas de lluvia',
            'Calzado semiformal para hombre',
            'Botas para hombre',
            'Chanclos y zuecos para hombre',
            'Botas de nieve para hombre',
        ],
    },
    {
        name: 'Calzado de mujer',
        subcategories: [
            'Chanclas de mujer',
            'Calzado deportivo para mujer',
            'Sandalias con plataforma y cuña para mujer',
            'Botas sobre la rodilla para mujer',
            'Sandalias planas para mujer',
            'Sandalias de tacón de mujer',
            'Sandalias para mujer',
            'Botas hasta la rodilla para mujer',
            'Calzado Oxford para mujer',
            'Pantuflas para mujer',
            'Botines de mujer',
            'Tacones para mujer',
            'Mocasines y sandalias para mujer',
            'Botas de media pantorrilla para mujer',
            'Calzado plano para mujer',
            'Zapatos de trabajo y seguridad para mujer',
            'Chanclos y zuecos para mujer',
            'Accesorios para calzado',
            'Calzado de lona para mujer',
            'Decoración de zapatos encantos',
        ],
    },
    {
        name: 'Calzado para niños',
        subcategories: [
            'Sandalias y pantuflas para niño',
            'Atlético para niña',
            'Calzado deportivo para niña',
            'Sandalias y pantuflas para niña',
            'Calzado deportivo para niño',
            'Zapatos con tacón de niña',
            'Atlético para niño',
            'Calzado casual para niño bebé',
            'Mocasines y sandalias para niña',
            'Calzado para niña bebé',
            'Botas para niña',
            'Botas para niño',
            'Calzado y sandalias para niño',
            'Chanclos y zuecos de niño',
            'Chanclos y zuecos de niña',
        ],
    },
    {
        name: 'Deporte al aire libre',
        subcategories: [
            'Accesorios deportivos para mujer',
            'Zapatos de agua para mujer',
            'Ropa de yoga',
            'Calzado de correr para mujer',
            'Electrónica y gadgets deportivos',
            'Ropa para deportes acuáticos para hombre',
            'Calzado deportivo para hombre',
            'Ropa de deportes de invierno para mujer',
            'Sandalias deportivas para mujer',
            'Zapatos de baile para mujer',
            'Ropa de exterior para mujer',
            'Botas de lluvia para mujer',
            'Calzado deportivo y de exterior para niños',
            'Calzado deportivo para mujer',
            'Ropa deportiva de hombre',
            'Medicina deportiva',
            'Iluminación exterior',
            'Accesorios para exterior y deportes',
            'Gorras y accesorios para la cabeza al aire libre',
            'Artículos de ejercicio y fitness',
            'Ropa de exterior para hombre',
            'Zapatos de skate para mujer',
            'Yoga y fitness',
            'Deportes',
            'Ciclismo',
            'Bolsos y mochilas',
            'Natación, buceo y deportes acuáticos',
            'Ropa deportiva para mujer',
            'Picnic y cocina de campamento',
            'Botas de nieve para mujer',
            'Accesorios de ropa deportiva para mujeres',
            'Ropa deportiva de invierno para hombre',
            'Ropa deportiva y de exterior de niño',
            'Ropa para correr y fitness para hombre',
            'Ropa deportiva para hombre',
            'Sala de juegos y patio',
            'Accesorios de caza y tácticos',
            'Pesca',
            'Campamento y senderismo',
            'Golf',
            'Suministros al aire libre para mujeres',
            'Deportes de invierno',
            'Artículos de barco',
            'Equipo de escala y supervivencia',
        ],
    },
    {
        name: 'Electrodomésticos',
        subcategories: [
            'Electrónicos para el cuidado bucal',
            'Exprimidores y procesadores de alimentos',
            'Calidad del aire',
            'Electrónica de cuidado personal',
            'Monitores de salud y bienestar',
            'Pequeños electrodomésticos',
            'Artículos de lavandería',
            'Electrodomésticos de cocina',
            'Neveras, Congeladores y Complementos',
            'Repelentes ultrasónicos de plagas',
            'Aspiradoras y cuidado de pisos',
            'Ventiladores y aires acondicionados',
            'Masajeadores eléctricos',
            'Electrodomésticos para el hogar',
            'Maquina de hielo',
            'Equipo de calefacción',
        ],
    },
    {
        name: 'Herramientas y hogar',
        subcategories: [
            'Cámaras de vigilancia',
            'Herramientas eléctricas',
            'Linternas',
            'Iluminación navideña',
            'Soldadura y corte',
            'Adhesivos y selladores',
            'Papel tapiz autoadhesivo',
            'Herramientas de medición y diseño',
            'Equipo de protección personal',
            'Seguridad y protección',
            'Electrodomésticos y accesorios',
            'Eléctrico',
            'Fontanería y plomería',
            'Iluminación y ventiladores de techo',
            'Accesorios de cocina',
            'Tiras de luces LED',
            'Tomas de corriente y accesorios',
            'Herramienta de pintura',
            'Piezas y accesorios de herramientas eléctricas',
            'Cerraduras',
            'Pegatinas de pared y murales',
            'Herramientas manuales',
            'Bombillas',
            'Accesorios de baño',
            'Organizadores de herramientas',
            'Preparación de invierno',
            'Organización de almacenamiento y hogar',
            'Materiales de construcción',
            'Herramientas de jardinería',
        ],
    },
    {
        name: 'Hogar inteligente',
        subcategories: [
            'Iluminación inteligente',
            'Enchufes y tomacorrientes',
            'Seguridad y vigilancia',
            'Reloj inteligente y accesorios',
            'WIFI y redes',
            'Entretenimiento de hogar',
            'Timbres y cerraduras inteligentes',
            'Dispositivos inteligentes',
        ],
    },
    {
        name: 'Hogar y cocina',
        subcategories: [
            'Conjuntos de ropa de playa para mujeres',
            'Pantalones cortos moldeadores para mujer',
            'Traje de baño Rash Guard para mujer',
            'Sujetadores y bralettes para mujer',
            'Accesorios deportivos para mujer',
            'Corsés y Bustiers para Mujer',
            'Sujetador deportivo para mujer',
            'Ropa moldeadora de hombre',
            'Zapatos de agua para mujer',
            'Maletines',
            'Seguridad',
            'Monos para mujer',
            'Pantuflas para hombre',
            'Ropa de yoga',
            'Fajas para mujer',
            'Trajes de baño para mujeres',
            'Sandalias y pantuflas para niño',
            'Blazers para mujer',
            'Conjunto de lencería para mujer',
            'Calzado de patinar para hombre',
            'Tankinis para mujeres',
            'Pantaletas de cintura alta para mujer',
            'Sesión de fotos',
            'Pantalones cargo para hombre',
            'Panties para mujer',
            'Calzado de trabajo y seguridad para hombre',
            'Atlético para niña',
            'Chanclas de mujer',
            'Bralette de mujer',
        ],
    },
    {
        name: 'Hombre de talla grande',
        subcategories: [
            'Jeans de talla grande para hombre',
            'Camisas de hombre talla grande',
            'Conjuntos deportivos talla grande',
            'Trajes y piezas de talla grande para hombre',
            'Pantalones cargo de talla grande para hombre',
            'Trajes de baño de talla grande para hombre',
            'Prendas inferiores de talla grande para hombre',
            'Polos de talla grande para hombre',
            'Hoodies y sudaderas de talla grande para hombre',
            'Prendas superiores de talla grande para hombre',
            'Shorts de talla grande de hombre',
            'Camisetas de talla grande para hombre',
            'Camisetas sin mangas de hombre talla grande',
        ],
    },
    {
        name: 'Instrumentos musicales',
        subcategories: [
            'Grabación en estudio y en vivo',
            'Instrumentos de viento, metal y madera',
            'Batería y percusión',
            'Teclados y MIDIs',
            'Accesorios para instrumentos',
            'Instrumentos de cuerda',
        ],
    },
    {
        name: 'Joyería y accesorios',
        subcategories: [
            'Relojes para mujer',
            'Relojes para hombre',
            'Gafas para mujer',
            'Gafas para hombre',
            'Accesorios para reloj',
            'Productos personalizados',
            'Cinturones para hombre',
            'Abanicos de mano',
            'Cinturones para mujer',
            'Guantes y manoplas para hombre',
            'Sombreros y gorras para hombre',
            'Tiradores para hombre',
            'Joyeros y organizadores',
            'Sombreros y gorras para mujer',
            'Cobertura facial',
            'Accesorios para el cabello',
            'Accesorios para gafas de mujer',
            'Limpieza y cuidado de joyas',
            'Joyas para mujer',
            'Cuello falso de mujer',
            'Bufandas y pañuelos para mujer',
            'Accesorios de boda para mujer',
            'Accesorios para hombre',
            'Corbatas y accesorios para hombre',
            'Pelucas de hombres',
            'Guantes y manoplas para mujer',
            'Accesorios para disfraces de mujer',
            'Llaveros de hombre',
            'Bufandas para hombre',
            'Joyas para hombre',
            'Llaveros y llaveros de mujer',
            'Botones y pines de mujer',
            'Accesorios para hacer joyas',
            'Parches de apliques',
            'Orejeras para hombre',
            'orejeras de mujer',
            'Piedras preciosas sueltas',
        ],
    },
    {
        name: 'Juguetes',
        subcategories: [
            'Drones y Juguetes Voladores',
            'Juguetes electrónicos',
            'Juguetes para bebé e infante',
            'Novedades y disfraces',
            'Vehículos',
            'Aprendizaje y educación',
            'Armas de juguete y accesorios',
            'Instrumentos musicales para niños',
            'Muñecas y accesorios',
            'Figuras de juguete y sets de juego',
            'Juegos y accesorios',
            'Juguetes de construcción',
            'Dibujo y pintura',
            'Juguetes novedosos y de broma',
            'Rompecabezas',
            'Marionetas y teatros de marionetas',
            'Juegos de simulación',
            'Deportes y juegos al aire libre',
            'Juguetes de agua',
            'Artículos de fiesta',
            'Peluches y juguetes de felpa',
            'Materiales para manualidades y pegatinas',
        ],
    },
    {
        name: 'Lencería y pijama para mujer',
        subcategories: [
            'Pantalones cortos moldeadores para mujer',
            'Sujetadores y bralettes para mujer',
            'Corsés y Bustiers para Mujer',
            'Sujetador deportivo para mujer',
            'Fajas para mujer',
            'Conjunto de lencería para mujer',
            'Pantaletas de cintura alta para mujer',
            'Panties para mujer',
            'Bralette de mujer',
            'Ropa de dormir para mujer',
            'Vestido y faldas de mujer',
            'Accesorios de lencería de mujer',
            'Medias y calcetines para mujer',
            'Lencería sexy para mujer',
            'Ropa de descanso para mujer',
        ],
    },
    {
        name: 'Libros',
        subcategories: [
            'Libros para niños',
            'Ciencia y Matemáticas',
            'Referencia',
            'Educación y Formación',
            'Literatura y Fantasía',
            'Adolescentes y adultos jóvenes',
            'Negocios y Finanzas',
            'Informática y Tecnología',
        ],
    },
    {
        name: 'Manualidades',
        subcategories: [
            'Estambre e hilado',
            'Artículos para fundición de Joyas',
            'Construcción de modelos y hobbies',
            'Telas',
            'Bisutería y fabricación de joyas',
            'Productos personalizados',
            'Herramientas para tejer y crochet',
            'Envoltura de regalos',
            'Decoración de fiestas',
            'Bordado y tejido',
            'Costura',
            'Organización y almacenamiento',
            'Manualidades',
            'Scrapbooking y estampación',
            'Pintura, dibujo y arte',
        ],
    },
    {
        name: 'Mascotas',
        subcategories: [
            'Collares, correas y arneses para mascotas',
            'Artículos para caballos',
            'Aseo de mascotas',
            'Ropa y accesorios de mascota',
            'Cuencos y comederos',
            'Productos personalizados',
            'Transportador y productos de viaje',
            'Limpieza de mascotas',
            'Camas y Accesorios para Mascotas',
            'Entrenamiento y comportamiento',
            'Juguetes para mascotas',
            'Peces, reptiles y anfibios',
            'Muebles para Mascotas',
            'Animales pequeños',
            'Aves',
            'Memoriales y funerales para mascotas',
            'Otros para mascotas',
        ],
    },
    {
        name: 'Moda infantil',
        subcategories: [
            'Ropa de baño de niño',
            'Relojes para niños',
            'Bolsas para niños',
            'Vestidos de bebé',
            'Vestidos para niña',
            'Bottoms de bebé',
            'Traje de baño de niña',
            'Ropa interior y pijamas',
            'Accesorios para niños',
            'Gafas de sol para niños',
            'Disfraces y accesorios',
            'Conjuntos para niña',
            'Conjuntos de niño',
            'Mamelucos para bebé',
            'Corbatas, Cinturones y Accesorios',
            'Accesorios para bebés',
            'Accesorios para el cabello de niños',
            'Pantalones para niña',
            'Pantalones para niño',
            'Conjuntos de bebé',
            'Mochilas para niños',
            'Camisas para niña',
            'Sombreros y gorras para niños',
            'Camisas para niño',
            'Guantes y bufandas para niños',
            'Botones y prendedores para niños',
            'Tops de bebé',
            'Joyería para niños',
            'Superiores para niña',
            'Camisetas para niña',
            'Superiores para niño',
            'Camisetas para niño',
        ],
    },
    {
        name: 'Mujer curvy',
        subcategories: [
            'Blusas curvy',
            'Monos y bodys para mujer curvy',
            'Mezclilla para mujer curvy',
            'Pantalones para mujer curvy',
            'Abrigos y chaquetas para mujer curvy',
            'Ropa interior para mujer curvy',
            'Trajes para mujer curvy',
            'Vestidos de boda para mujer curvy',
            'Vestidos para mujer curvy',
            'Faldas curvy',
            'Conjuntos para mujer curvy',
            'Prendas tejidas para mujer curvy',
            'Lencería sexy y disfraces para mujer curvy',
            'Curvas Pantalones Deportivos',
            'Shorts curvy',
            'Cárdigans curvy',
            'Sujetadores deportivos curvos',
            'Trajes deportivos curvos',
            'Ropa de casa y pijamas para mujer curvy',
            'Leggings curvy',
            'Camisola curvy y camisetas sin mangas',
            'Ropa tradicional para mujer curvy',
            'Vestido deportivo curvo',
            'Camisetas para mujer curvy',
            'Curvas Conjuntos Deportivos',
            'Sudaderas para mujer curvy',
            'Chaquetas deportivas curvas',
            'Camisetas deportivas curvas',
        ],
    },
    {
        name: 'Negocios, Industria y Ciencias',
        subcategories: [
            'Iluminación comercial',
            'Herramientas eléctricas',
            'Prueba, medición e inspección',
            'Salud y seguridad laboral',
            'Artículos dentales profesionales',
            'Herramientas manuales',
            'Productos abrasivos y de acabado',
            'Herramientas para cortar',
            'Electrónica Industrial',
            'Enseñanza de ciencia',
            'Artículos médicos profesionales',
            'Sujetadores',
            'Adhesivos y selladores',
            'Accesorios y equipo para tiendas',
            'Impresoras 3D y accesorios',
            'Hidráulico, neumático y fontanería',
            'Embalaje y envío',
            'Ferretería industrial',
            'Suministros de limpieza y sanitarios',
            'Artículos científicos y de laboratorio',
            'Equipo y suministros de servicio de alimentos',
            'Manejo de materiales',
            'Muebles comerciales',
            'Materiales industriales',
        ],
    },
    {
        name: 'Oficina y escuela',
        subcategories: [
            'Electrónicos de oficina',
            'Iluminación de oficina',
            'Estuches de transporte',
            'Almacenamiento y organización',
            'Artículos para escritura y corrección',
            'Productos personalizados',
            'Embalaje y envío',
            'Cinta, adhesivos y fijadores',
            'Papel, etiquetas e índices',
            'Accesorios de escritorio',
            'Oficina y escolares',
            'Envoltura de regalos y manualidades',
            'Muebles y repuestos de oficina',
            'Pegatinas de papelería',
            'Escritorios y estaciones de trabajo',
            'Sillas y Sofás',
            'Decoraciones para el aula',
            'Tarjetas de felicitación y postales',
        ],
    },
    {
        name: 'Patio, césped y jardín',
        subcategories: [
            'Iluminación para exteriores',
            'Generadores y energía portátil',
            'Luces navideñas para exterior',
            'Cuidado del ganado y abejas en el patio',
            'Cortacésped y herramientas eléctricas para exteriores',
            'Piscinas y bañeras',
            'Riego y irrigación',
            'Jardines con agua y estanques',
            'Control de plagas',
            'Herramientas de jardinería',
            'Parrillas y cocina al aire libre',
            'Cubiertas para muebles de patio',
            'Decoración exterior',
            'Invernaderos y luces de cultivo',
            'Almacenamiento para exteriores',
            'Cuidado de aves y vida silvestre',
            'Jardineras y contenedores',
            'Termómetros e instrumentos meteorológicos',
            'Soporte y cuidado de plantas',
            'Estacas decorativas para jardín',
            'Esculturas de jardín',
            'Carros y Picnic al aire libre',
            'Retirada de nieve',
            'Marquesinas, cenadores y pérgolas',
            'Muebles de patio',
            'Letreros de jardín y arte de pared',
            'Calefacción y refrigeración al aire libre',
            'Plantas, Semillas y Bulbos',
        ],
    },
    {
        name: 'Ropa de hombre',
        subcategories: [
            'Pantalones cargo para hombre',
            'Chaquetas y abrigos para hombre',
            'Pantalones para hombre',
            'Jeans para hombre',
            'Suéteres para hombre',
            'Trajes y piezas separadas para hombre',
            'Prendas superiores para hombre',
            'Camisas informales y de vestir para hombre',
            'Camisas polos de hombre',
            'Trajes de baño de hombre',
            'Conjuntos para hombre',
            'Pantalones casuales para hombre',
            'Shorts para hombre',
            'Hombre de talla grande',
            'Camisetas sin mangas para hombre',
            'Hoodies y sudaderas para hombre',
            'Camisetas para hombre',
        ],
    },
    {
        name: 'Ropa de mujer',
        subcategories: [
            'Monos para mujer',
            'Blazers para mujer',
            'Mezclilla para mujer',
            'Faldas de mezclilla de mujer',
            'Bodys para mujer',
            'Blusas y camisas para mujer',
            'Ropa de exterior para mujer',
            'Chaquetas y abrigos de mezclilla para mujer',
            'Jeans para mujer',
            'Uniformes de mujer, trabajo y seguridad',
            'Pantalones para mujer',
            'Ropa para bodas de mujer',
            'Conjuntos para mujer',
            'Faldas para mujer',
            'Vestidos de mujer',
            'Shorts de mezclilla para mujer',
            'Ropa cosplay para mujer',
            'Camisetas y tops de tirantes de mujer',
            'Shorts para mujer',
            'Ropa de maternidad',
            'Suéteres para mujer',
            'Pantalones ajustados para mujer',
            'Camisetas de mujer',
            'Ropa tradicional y cultural para mujeres',
            'Ropa deportiva para mujer',
            'Sudaderas para mujer',
            'Sudaderas deportivas',
        ],
    },
    {
        name: 'Ropa de playa',
        subcategories: [
            'Conjuntos de ropa de playa para mujeres',
            'Traje de baño Rash Guard para mujer',
            'Trajes de baño para mujeres',
            'Tankinis para mujeres',
            'Conjuntos de bikini para mujeres',
            'Ropa de playa para mujeres',
            'Shorts de playa para mujeres',
            'Parte de abajo de bikini para mujeres',
            'Tops de bikini para mujeres',
            'Trajes de baño con estampado de curvas',
            'Trajes de baño de una sola pieza',
            'Parte inferior de trajes de baño con curvas',
            'Ocultar las curvas',
            'Conjuntos de bikini de curvas',
            'Tops de bikini con forma curva',
        ],
    },
    {
        name: 'Ropa interior y pijamas de hombre',
        subcategories: [
            'Ropa moldeadora de hombre',
            'Ropa interior para hombre',
            'Ropa interior térmica',
            'Calcetines para hombre',
            'Ropa de descanso para hombre',
            'Ropa exótica\xa0para hombre',
            'Ropa novedosa para hombre',
        ],
    },
    {
        name: 'Salud y hogar',
        subcategories: [
            'Productos de cuidado bucal',
            'Salud del pie',
            'Cuidado personal',
            'Masajeadores eléctricos',
            'Productos para el cuidado de la salud',
            'Productos personalizados',
            'Cuidado de la visión',
            'Control de insectos y plagas en interiores',
            'Hogar y limpieza',
            'Uso médico para el hogar',
            'Herramientas de masaje',
            'Productos de bienestar y relajación',
            'Tabaquería y encendedores',
            'Productos de bienestar sexual',
            'Papelería y envoltura para regalo',
        ],
    },
    {
        name: 'Tecnología',
        subcategories: [
            'Audio y radio',
            'Iluminación',
            'Dispositivos USB',
            'Tiras de alimentación',
            'Almacenamiento de datos',
            'Audífonos, auriculares y accesorios',
            'Accesorios de computadora',
            'Teclados, mouse y accesorios',
            'Concentradores y adaptadores',
            'Componentes de computadora',
            'Fotos y Óptica',
            'Videojuegos',
            'Baterías y accesorios',
            'Tabletas, portátiles y accesorios',
            'Pegatinas para portátiles y tabletas',
        ],
    },
    {
        name: 'Teléfonos y más',
        subcategories: [
            'Sesión de fotos',
            'Cargadores inalámbricos',
            'Accesorios telefónicos',
            'Cargadores',
            'Cables y adaptadores',
            'Soportes',
            'Mantenimiento, conservación y reparaciones',
            'Decoración',
            'Estuches, carcasas y fundas',
        ],
    },
];
