export const countries = [
    {
        nombre: 'Albania',
        name: 'Albania',
        nom: 'Albanie',
        iso2: 'AL',
        iso3: 'ALB',
        phone_code: '355',
    },
    {
        nombre: 'Alemania',
        name: 'Germany',
        nom: 'Allemagne',
        iso2: 'DE',
        iso3: 'DEU',
        phone_code: '49',
    },
    {
        nombre: 'Andorra',
        name: 'Andorra',
        nom: 'Andorra',
        iso2: 'AD',
        iso3: 'AND',
        phone_code: '376',
    },
    {
        nombre: 'Arabia Saudita',
        name: 'Saudi Arabia',
        nom: 'Arabie Saoudite',
        iso2: 'SA',
        iso3: 'SAU',
        phone_code: '966',
    },
    {
        nombre: 'Argelia',
        name: 'Algeria',
        nom: 'Algérie',
        iso2: 'DZ',
        iso3: 'DZA',
        phone_code: '213',
    },
    {
        nombre: 'Armenia',
        name: 'Armenia',
        nom: "L'Arménie",
        iso2: 'AM',
        iso3: 'ARM',
        phone_code: '374',
    },
    {
        nombre: 'Australia',
        name: 'Australia',
        nom: 'Australie',
        iso2: 'AU',
        iso3: 'AUS',
        phone_code: '61',
    },
    {
        nombre: 'Austria',
        name: 'Austria',
        nom: 'Autriche',
        iso2: 'AT',
        iso3: 'AUT',
        phone_code: '43',
    },
    {
        nombre: 'Azerbaiyán',
        name: 'Azerbaijan',
        nom: "L'Azerbaïdjan",
        iso2: 'AZ',
        iso3: 'AZE',
        phone_code: '994',
    },
    {
        nombre: 'Baréin',
        name: 'Bahrain',
        nom: 'Bahreïn',
        iso2: 'BH',
        iso3: 'BHR',
        phone_code: '973',
    },
    {
        nombre: 'Bélgica',
        name: 'Belgium',
        nom: 'Belgique',
        iso2: 'BE',
        iso3: 'BEL',
        phone_code: '32',
    },
    {
        nombre: 'Brasil',
        name: 'Brazil',
        nom: 'Brésil',
        iso2: 'BR',
        iso3: 'BRA',
        phone_code: '55',
    },
    {
        nombre: 'Bulgaria',
        name: 'Bulgaria',
        nom: 'Bulgarie',
        iso2: 'BG',
        iso3: 'BGR',
        phone_code: '359',
    },
    {
        nombre: 'Bosnia y Herzegovina',
        name: 'Bosnia and Herzegovina',
        nom: 'Bosnie-Herzégovine',
        iso2: 'BA',
        iso3: 'BIH',
        phone_code: '387',
    },
    {
        nombre: 'Brunéi Darussalam',
        name: 'Brunei Darussalam',
        nom: 'Brunei Darussalam',
        iso2: 'BN',
        iso3: 'BRN',
        phone_code: '673',
    },
    {
        nombre: 'Catar',
        name: 'Qatar',
        nom: 'Qatar',
        iso2: 'QA',
        iso3: 'QAT',
        phone_code: '974',
    },
    {
        nombre: 'Canadá',
        name: 'Canada',
        nom: 'Canada',
        iso2: 'CA',
        iso3: 'CAN',
        phone_code: '1',
    },
    {
        nombre: 'Chile',
        name: 'Chile',
        nom: 'Chili',
        iso2: 'CL',
        iso3: 'CHL',
        phone_code: '56',
    },
    {
        nombre: 'Chipre',
        name: 'Cyprus',
        nom: 'Chypre',
        iso2: 'CY',
        iso3: 'CYP',
        phone_code: '357',
    },
    {
        nombre: 'Colombia',
        name: 'Colombia',
        nom: 'Colombie',
        iso2: 'CO',
        iso3: 'COL',
        phone_code: '57',
    },
    {
        nombre: 'Corea del Sur',
        name: 'South Korea',
        nom: 'Corée du Sud',
        iso2: 'KR',
        iso3: 'KOR',
        phone_code: '82',
    },
    {
        nombre: 'Croacia',
        name: 'Croatia',
        nom: 'Croatie',
        iso2: 'HR',
        iso3: 'HRV',
        phone_code: '385',
    },
    {
        nombre: 'Dinamarca',
        name: 'Denmark',
        nom: 'Danemark',
        iso2: 'DK',
        iso3: 'DNK',
        phone_code: '45',
    },
    {
        nombre: 'Ecuador',
        name: 'Ecuador',
        nom: 'Equateur',
        iso2: 'EC',
        iso3: 'ECU',
        phone_code: '593',
    },
    {
        nombre: 'El Salvador',
        name: 'El Salvador',
        nom: 'El Salvador',
        iso2: 'SV',
        iso3: 'SLV',
        phone_code: '503',
    },
    {
        nombre: 'Emiratos Árabes Unidos',
        name: 'United Arab Emirates',
        nom: 'Emirats Arabes Unis',
        iso2: 'AE',
        iso3: 'ARE',
        phone_code: '971',
    },
    {
        nombre: 'Estados Unidos',
        name: 'United States of America',
        nom: "États-Unis d'Amérique",
        iso2: 'US',
        iso3: 'USA',
        phone_code: '1',
    },
    {
        nombre: 'Eslovaquia',
        name: 'Slovakia',
        nom: 'Slovaquie',
        iso2: 'SK',
        iso3: 'SVK',
        phone_code: '421',
    },
    {
        nombre: 'Eslovenia',
        name: 'Slovenia',
        nom: 'Slovénie',
        iso2: 'SI',
        iso3: 'SVN',
        phone_code: '386',
    },
    {
        nombre: 'España',
        name: 'Spain',
        nom: 'Espagne',
        iso2: 'ES',
        iso3: 'ESP',
        phone_code: '34',
    },
    {
        nombre: 'Estonia',
        name: 'Estonia',
        nom: "L'Estonie",
        iso2: 'EE',
        iso3: 'EST',
        phone_code: '372',
    },
    {
        nombre: 'Filipinas',
        name: 'Philippines',
        nom: 'Philippines',
        iso2: 'PH',
        iso3: 'PHL',
        phone_code: '63',
    },
    {
        nombre: 'Finlandia',
        name: 'Finland',
        nom: 'Finlande',
        iso2: 'FI',
        iso3: 'FIN',
        phone_code: '358',
    },
    {
        nombre: 'Francia',
        name: 'France',
        nom: 'France',
        iso2: 'FR',
        iso3: 'FRA',
        phone_code: '33',
    },
    {
        nombre: 'Georgia',
        name: 'Georgia',
        nom: 'Géorgie',
        iso2: 'GE',
        iso3: 'GEO',
        phone_code: '995',
    },
    {
        nombre: 'Grecia',
        name: 'Greece',
        nom: 'Grèce',
        iso2: 'GR',
        iso3: 'GRC',
        phone_code: '30',
    },
    {
        nombre: 'Guam',
        name: 'Guam',
        nom: 'Guam',
        iso2: 'GU',
        iso3: 'GUM',
        phone_code: '1 671',
    },
    {
        nombre: 'Guatemala',
        name: 'Guatemala',
        nom: 'Guatemala',
        iso2: 'GT',
        iso3: 'GTM',
        phone_code: '502',
    },
    {
        nombre: 'Hungría',
        name: 'Hungary',
        nom: 'Hongrie',
        iso2: 'HU',
        iso3: 'HUN',
        phone_code: '36',
    },
    {
        nombre: 'Islas Vírgenes (EE.UU.)',
        name: 'United States Virgin Islands',
        nom: 'Îles Vierges américaines',
        iso2: 'VI',
        iso3: 'VIR',
        phone_code: '1 340',
    },
    {
        nombre: 'Irlanda',
        name: 'Ireland',
        nom: 'Irlande',
        iso2: 'IE',
        iso3: 'IRL',
        phone_code: '353',
    },
    {
        nombre: 'Islandia',
        name: 'Iceland',
        nom: 'Islande',
        iso2: 'IS',
        iso3: 'ISL',
        phone_code: '354',
    },
    {
        nombre: 'Islas Marianas del Norte',
        name: 'Northern Mariana Islands',
        nom: 'Iles Mariannes du Nord',
        iso2: 'MP',
        iso3: 'MNP',
        phone_code: '1 670',
    },
    {
        nombre: 'Israel',
        name: 'Israel',
        nom: 'Israël',
        iso2: 'IL',
        iso3: 'ISR',
        phone_code: '972',
    },
    {
        nombre: 'Italia',
        name: 'Italy',
        nom: 'Italie',
        iso2: 'IT',
        iso3: 'ITA',
        phone_code: '39',
    },
    {
        nombre: 'Japón',
        name: 'Japan',
        nom: 'Japon',
        iso2: 'JP',
        iso3: 'JPN',
        phone_code: '81',
    },
    {
        nombre: 'Jordania',
        name: 'Jordan',
        nom: 'Jordan',
        iso2: 'JO',
        iso3: 'JOR',
        phone_code: '962',
    },
    {
        nombre: 'Kazajistán',
        name: 'Kazakhstan',
        nom: 'Le Kazakhstan',
        iso2: 'KZ',
        iso3: 'KAZ',
        phone_code: '7',
    },
    {
        nombre: 'Kuwait',
        name: 'Kuwait',
        nom: 'Koweït',
        iso2: 'KW',
        iso3: 'KWT',
        phone_code: '965',
    },
    {
        nombre: 'Letonia',
        name: 'Latvia',
        nom: 'La Lettonie',
        iso2: 'LV',
        iso3: 'LVA',
        phone_code: '371',
    },
    {
        nombre: 'Lituania',
        name: 'Lithuania',
        nom: 'La Lituanie',
        iso2: 'LT',
        iso3: 'LTU',
        phone_code: '370',
    },
    {
        nombre: 'Luxemburgo',
        name: 'Luxembourg',
        nom: 'Luxembourg',
        iso2: 'LU',
        iso3: 'LUX',
        phone_code: '352',
    },
    {
        nombre: 'México',
        name: 'Mexico',
        nom: 'Mexique',
        iso2: 'MX',
        iso3: 'MEX',
        phone_code: '52',
    },
    {
        nombre: 'Malasia',
        name: 'Malaysia',
        nom: 'Malaisie',
        iso2: 'MY',
        iso3: 'MYS',
        phone_code: '60',
    },
    {
        nombre: 'Macedonia del Norte',
        name: 'Macedonia',
        nom: 'Macédoine',
        iso2: 'MK',
        iso3: 'MKD',
        phone_code: '389',
    },
    {
        nombre: 'Malta',
        name: 'Malta',
        nom: 'Malte',
        iso2: 'MT',
        iso3: 'MLT',
        phone_code: '356',
    },
    {
        nombre: 'Marruecos',
        name: 'Morocco',
        nom: 'Maroc',
        iso2: 'MA',
        iso3: 'MAR',
        phone_code: '212',
    },
    {
        nombre: 'Mauricio',
        name: 'Mauritius',
        nom: 'Iles Maurice',
        iso2: 'MU',
        iso3: 'MUS',
        phone_code: '230',
    },
    {
        nombre: 'Moldavia',
        name: 'Moldova',
        nom: 'Moldavie',
        iso2: 'MD',
        iso3: 'MDA',
        phone_code: '373',
    },
    {
        nombre: 'Montenegro',
        name: 'Montenegro',
        nom: 'Monténégro',
        iso2: 'ME',
        iso3: 'MNE',
        phone_code: '382',
    },
    {
        nombre: 'Nigeria',
        name: 'Nigeria',
        nom: 'Nigeria',
        iso2: 'NG',
        iso3: 'NGA',
        phone_code: '234',
    },
    {
        nombre: 'Noruega',
        name: 'Norway',
        nom: 'Norvège',
        iso2: 'NO',
        iso3: 'NOR',
        phone_code: '47',
    },
    {
        nombre: 'Nueva Zelanda',
        name: 'New Zealand',
        nom: 'Nouvelle-Zélande',
        iso2: 'NZ',
        iso3: 'NZL',
        phone_code: '64',
    },
    {
        nombre: 'Omán',
        name: 'Oman',
        nom: 'Oman',
        iso2: 'OM',
        iso3: 'OMN',
        phone_code: '968',
    },
    {
        nombre: 'Países Bajos',
        name: 'Netherlands',
        nom: 'Pays-Bas',
        iso2: 'NL',
        iso3: 'NLD',
        phone_code: '31',
    },
    {
        nombre: 'Pakistán',
        name: 'Pakistan',
        nom: 'Pakistan',
        iso2: 'PK',
        iso3: 'PAK',
        phone_code: '92',
    },
    {
        nombre: 'Panamá',
        name: 'Panama',
        nom: 'Panama',
        iso2: 'PA',
        iso3: 'PAN',
        phone_code: '507',
    },
    {
        nombre: 'Perú',
        name: 'Peru',
        nom: 'Pérou',
        iso2: 'PE',
        iso3: 'PER',
        phone_code: '51',
    },
    {
        nombre: 'Polonia',
        name: 'Poland',
        nom: 'Pologne',
        iso2: 'PL',
        iso3: 'POL',
        phone_code: '48',
    },
    {
        nombre: 'Portugal',
        name: 'Portugal',
        nom: 'Portugal',
        iso2: 'PT',
        iso3: 'PRT',
        phone_code: '351',
    },
    {
        nombre: 'Puerto Rico',
        name: 'Puerto Rico',
        nom: 'Porto Rico',
        iso2: 'PR',
        iso3: 'PRI',
        phone_code: '1',
    },
    {
        nombre: 'Reino Unido',
        name: 'United Kingdom',
        nom: 'Royaume-Uni',
        iso2: 'GB',
        iso3: 'GBR',
        phone_code: '44',
    },
    {
        nombre: 'República Checa',
        name: 'Czech Republic',
        nom: 'République Tchèque',
        iso2: 'CZ',
        iso3: 'CZE',
        phone_code: '420',
    },
    {
        nombre: 'República Dominicana',
        name: 'Dominican Republic',
        nom: 'République Dominicaine',
        iso2: 'DO',
        iso3: 'DOM',
        phone_code: '1 809',
    },
    {
        nombre: 'Serbia',
        name: 'Serbia',
        nom: 'Serbie',
        iso2: 'RS',
        iso3: 'SRB',
        phone_code: '381',
    },
    {
        nombre: 'Sudáfrica',
        name: 'South Africa',
        nom: 'Afrique du Sud',
        iso2: 'ZA',
        iso3: 'ZAF',
        phone_code: '27',
    },
    {
        nombre: 'Suecia',
        name: 'Sweden',
        nom: 'Suède',
        iso2: 'SE',
        iso3: 'SWE',
        phone_code: '46',
    },
    {
        nombre: 'Suiza',
        name: 'Switzerland',
        nom: 'Suisse',
        iso2: 'CH',
        iso3: 'CHE',
        phone_code: '41',
    },
    {
        nombre: 'Tailandia',
        name: 'Thailand',
        nom: 'Thaïlande',
        iso2: 'TH',
        iso3: 'THA',
        phone_code: '66',
    },
    {
        nombre: 'Trinidad y Tobago',
        name: 'Trinidad and Tobago',
        nom: 'Trinidad et Tobago',
        iso2: 'TT',
        iso3: 'TTO',
        phone_code: '1 868',
    },
    {
        nombre: 'Turquía',
        name: 'Turkey',
        nom: 'Turquie',
        iso2: 'TR',
        iso3: 'TUR',
        phone_code: '90',
    },
    {
        nombre: 'Ucrania',
        name: 'Ukraine',
        nom: "L'Ukraine",
        iso2: 'UA',
        iso3: 'UKR',
        phone_code: '380',
    },
    {
        nombre: 'Uruguay',
        name: 'Uruguay',
        nom: 'Uruguay',
        iso2: 'UY',
        iso3: 'URY',
        phone_code: '598',
    },
    {
        nombre: 'Uzbekistán',
        name: 'Uzbekistan',
        nom: "L'Ouzbékistan",
        iso2: 'UZ',
        iso3: 'UZB',
        phone_code: '998',
    },
    {
        nombre: 'Vietnam',
        name: 'Vietnam',
        nom: 'Vietnam',
        iso2: 'VN',
        iso3: 'VNM',
        phone_code: '84',
    },
];
