export const countries = [
    'Albania',
    'Alemania',
    'Andorra',
    'Arabia Saudita',
    'Argelia',
    'Armenia',
    'Australia',
    'Austria',
    'Azerbaiyán',
    'Baréin',
    'Bélgica',
    'Bosnia-Herzegovina',
    'Brasil',
    'Brunéi Darusalam',
    'Bulgaria',
    'Canadá',
    'Catar',
    'Chile',
    'Chipre',
    'Colombia',
    'Corea del Sur',
    'Croacia',
    'Dinamarca',
    'Ecuador',
    'El Salvador',
    'Emiratos Árabes Unidos',
    'Eslovaquia',
    'Eslovenia',
    'España',
    'Estados Unidos',
    'Estonia',
    'Filipinas',
    'Finlandia',
    'Francia',
    'Georgia',
    'Grecia',
    'Guam',
    'Guatemala',
    'Hungría',
    'Irlanda',
    'Islandia',
    'Islas Marianas del Norte',
    'Islas Vírgenes (EE. UU.)',
    'Israel',
    'Italia',
    'Japón',
    'Jordania',
    'Kazajistán',
    'Kuwait',
    'Letonia',
    'Lituania',
    'Luxemburgo',
    'Macedonia del Norte',
    'Malasia',
    'Malta',
    'Marruecos',
    'Mauricio',
    'México',
    'Moldavia',
    'Montenegro',
    'Nigeria',
    'Noruega',
    'Nueva Zelanda',
    'Omán',
    'Países Bajos',
    'Pakistán',
    'Panamá',
    'Perú',
    'Polonia',
    'Portugal',
    'Puerto Rico',
    'Reino Unido',
    'República Checa',
    'República Dominicana',
    'Rumania',
    'Serbia',
    'Sudáfrica',
    'Suecia',
    'Suiza',
    'Tailandia',
    'Trinidad y Tobago',
    'Turquía',
    'Ucrania',
    'Uruguay',
    'Uzbekistán',
    'Vietnam',
];
