export const countryThemes = {
    ALB: { theme: 'Opening SALE' },
    DEU: { theme: 'Primavera de Ofertas' },
    AND: { theme: 'New Season Offers' },
    SAU: { theme: 'Autumn Savings 2' },
    DZA: { theme: 'New Season Offers' },
    ARM: { theme: 'Autumn Savings big 2' },
    AUS: { theme: 'Promocion de Otoño 2' },
    AUT: { theme: 'Promocion de Otoño 2' },
    AZE: { theme: 'PAYDAY SALE' },
    BHR: { theme: 'Early Autumn Deals' },
    BEL: { theme: 'Autumn Selections' },
    BRA: { theme: 'Primavera de Ofertas' },
    BGR: { theme: 'NATIONAL DAY' },
    BIH: { theme: 'Promocion de Otoño 3' },
    BRN: { theme: 'New Season Offers' },
    QAT: { theme: 'Autumn Savings 2' },
    CAN: { theme: 'Promocion de Otoño' },
    CHL: { theme: 'PAYDAY SALE' },
    CYP: { theme: 'Autumn Selections' },
    COL: { theme: 'Amor y Amistad' },
    KOR: { theme: 'Promocion de Otoño' },
    HRV: { theme: 'Early Autumn Offers' },
    DNK: { theme: 'Early Autumn Deals' },
    ECU: { theme: 'PREBAJAS DE VERANO' },
    SLV: { theme: 'Promocion de Otoño' },
    ARE: { theme: 'NATIONAL DAY' },
    USA: { theme: 'Early Spring Offers' },
    SVK: { theme: 'Early Autumn Savings' },
    SVN: { theme: 'Autumn Selections' },
    ESP: { theme: 'Early Autumn' },
    EST: { theme: 'Autumn Savings big 2' },
    PHL: { theme: 'Promocion de Otoño 2' },
    FIN: { theme: 'Opening SALE' },
    FRA: { theme: 'Autumn Savings 2' },
    GEO: { theme: 'Spring Deals' },
    GRC: { theme: 'Anniversary Sale' },
    GUM: { theme: 'NATIONAL DAY' },
    GTM: { theme: 'Autumn Savings big 2' },
    HUN: { theme: 'Early Autumn Offers' },
    VIR: { theme: 'Promocion de Otoño 2' },
    IRL: { theme: 'REBAJAS DE TEMPORADA' },
    ISL: { theme: 'Anniversary Sale' },
    MNP: { theme: 'New Season Offers' },
    ISR: { theme: 'Fall into Savings' },
    ITA: { theme: 'Ofertas de Inicio de Otoño' },
    JOR: { theme: 'Primavera de Ofertas' },
    KAZ: { theme: 'Autumn Savings big' },
    KWT: { theme: 'Early Autumn' },
    LVA: { theme: 'Autumn Savings 2' },
    LTU: { theme: 'Promocion de Otoño 2' },
    LUX: { theme: 'REBAJAS DE TEMPORADA' },
    MEX: { theme: 'New Season Offers' },
    MYS: { theme: 'Autumn Selections' },
    MKD: { theme: 'Fall into Savings' },
    MLT: { theme: 'Early Autumn' },
    MAR: { theme: 'Autumn Savings' },
    MUS: { theme: 'Early Spring Offers' },
    MDA: { theme: 'Spring Deals' },
    MNE: { theme: 'Early Autumn Savings' },
    NGA: { theme: 'NATIONAL DAY' },
    NOR: { theme: 'New Season Offers' },
    NZL: { theme: 'Anniversary Sale' },
    OMN: { theme: 'REBAJAS DE TEMPORADA' },
    NLD: { theme: 'Fall into Savings' },
    PAK: { theme: 'Promocion de Otoño 2' },
    PAN: { theme: 'Autumn Savings big' },
    PER: { theme: 'Early Autumn Deals' },
    POL: { theme: 'Promocion de Otoño' },
    PRT: { theme: 'Early Autumn' },
    PRI: { theme: 'Fall into Savings' },
    GBR: { theme: 'Promocion de Otoño 3' },
    CZE: { theme: 'Amor y Amistad' },
    DOM: { theme: 'Early Autumn Savings' },
    SRB: { theme: 'Ofertas de Inicio de Otoño' },
    ZAF: { theme: 'Autumn Savings big 2' },
    SWE: { theme: 'Spring Deals' },
    CHE: { theme: 'Early Autumn Offers' },
    THA: { theme: 'OFERTAS DE PRIMAVERA' },
    TTO: { theme: 'Primavera de Ofertas' },
    TUR: { theme: 'Primavera de Ofertas' },
    UKR: { theme: 'Autumn Selections' },
    URY: { theme: 'Autumn Savings 2' },
    UZB: { theme: 'Fall into Savings' },
    VNM: { theme: 'Primavera de Ofertas' },
    JPN: { theme: 'japon' },
};
