export const products = [
    {
        title: '1pc Protector de colchón impermeable en capas (sin funda de almohada ni inserto de almohada) Suave y cómodo Funda de colchón de color sólido Ropa de cama Habitación de invitados Sábana ajustable impermeable solamente',
        offer: '85.481',
        price: '122.229',
        img: '1pc Protector de colchón imper.webp',
    },
    {
        title: '2 Unids/set Gorro De Satén De Color Sólido Gorro De Noche Elástico Clásico Gorro De Ducha De Baño Suave Gorros De Pelo Elásticos De Seda De Imitación Para Mujeres',
        offer: '4.757',
        price: '28.629',
        img: '2 Unids_set Gorro De Satén De .webp',
    },
    {
        title: '6 piezas de calzoncillos sólidos con ribete festoneado, bragas íntimas elásticas, cómodas y transpirables, lencería y ropa interior para mujer',
        offer: '29.018',
        price: '69.600',
        img: '6 piezas de calzoncillos sólid.webp',
    },
    {
        title: '2pcs Verano Infantil Niña Bebé Cintura Flor Decoración Chaleco Vestido De Malla + Chaqueta De Manga Corta Con Conjunto De Diadema',
        offer: '46.239',
        price: '118.158',
        img: '2pcs Verano Infantil Niña Bebé.webp',
    },
    {
        title: 'Set de 40 Lazos para el Cabello Encantadores - Bandas Elásticas de Colores Surtidos para Mujeres y Niñas, Ideales para Coletas y Trenzas',
        offer: '12.876',
        price: '32.797',
        img: 'Set de 40 Lazos para el Cabell.webp',
    },
    {
        title: 'Reloj de Pared Moderno Silencioso 3D - Estilo Nórdico, Manecillas y Números Luminosos, Fácil Instalación con Tira Adhesiva - Perfecto para Sala de Estar, Dormitorio, Decoración de Oficina',
        offer: '22.950',
        price: '40.550',
        img: 'Reloj de Pared Moderno Silenci.webp',
    },
    {
        title: 'Reloj inteligente resistente al agua, pantalla táctil completa de 4.65 cm con mensajes, responder llamadas, monitor de sueño, podómetro deportivo, alertas de información, para teléfonos iPhone/Android, reloj de fitness inteligente para mujeres/hombres, regalo de amigo, regalo de cumpleaños',
        offer: '76.550',
        price: '224.540',
        img: 'Reloj inteligente resistente a.webp',
    },
    {
        title: 'Nuevo Drone UAV Quadcopter E88: Cámaras Duales De Alta Definición, Mantenimiento De Altitud, Operación Con Un Solo Botón, Luces LED, Cosas Económicas El Artículo Más Barato Disponible Perfecto Para Principiantes, Regalos Para Hombres Y Cosas Para Adolescentes',
        offer: '127.598',
        price: '405.518',
        img: 'Nuevo Drone UAV Quadcopter E88.webp',
    },
    {
        title: 'Bálsamo Labial Hidratante con Tinte en 3 Tonos - Hidratante, Acabado Brillante para Todo Tipo de Piel',
        offer: '4.715',
        price: '12.779',
        img: 'Bálsamo Labial Hidratante con .webp',
    },
    {
        title: 'Mochila De Viaje De Gran Capacidad Para Computadora Portátil De Tamaño Pequeño Para Hombres, De Nylon Casual Para La Universidad [sin Cable USB]',
        offer: '43.308',
        price: '75.955',
        img: 'Mochila De Viaje De Gran Capac.webp',
    },
    {
        title: 'Set de Manicura y Pedicura de Temática de Mariposas de Lujo - Cortaúñas de Acero Inoxidable, Kit de Viaje Verde Claro con Empaque de Regalo',
        offer: '15.424',
        price: '26.950',
        img: 'Set de Manicura y Pedicura de .webp',
    },
    {
        title: 'Muñeca de bebé renacida durmiendo de 55 cm, de 22 pulgadas, suave y realista de silicona, juguete para niñas recién nacidas, regalo de cumpleaños para niñas, regalo de Halloween/Día de Acción de Gracias/Navidad, regalo de Pascua',
        offer: '222.360',
        price: '499.810',
        img: 'Muñeca de bebé renacida durmie.webp',
    },
    {
        title: '2 piezas de atuendo de manga corta con estampado de dinosaurio genial para niño, camiseta de cuello redondo y conjunto de pantalones cortos cómodos, ropa de verano para niños',
        offer: '26.407',
        price: '70.087',
        img: '2 piezas de atuendo de manga c.webp',
    },
    {
        title: '1par - Protectores de goma de silicona impermeable para lluvia, universal para todo tipo de calzado, material reutilizable y antideslizante',
        offer: '8.359',
        price: '17.293',
        img: '1par - Protectores de goma de .webp',
    },
    {
        title: 'Vestido De Línea A Con Cuello De Ojales, Detalles De Volantes Para Vacaciones, Vestido Sin Mangas Con Cintura Ajustada Para Primavera Y Verano, Ropa De Mujer',
        offer: '66.451',
        price: '169.962',
        img: 'Vestido De Línea A Con Cuello .webp',
    },
    {
        title: 'Auriculares inalámbricos inteligentes E7S con micrófono, pantalla LED, para iPhone/Xiaomi, auriculares TWS unisex',
        offer: '38.327',
        price: '59.528',
        img: 'Auriculares inalámbricos intel.webp',
    },
    {
        title: 'Pantalla 3D de 100 pulgadas 4K, adecuada para cine en casa, proyector de pantalla para interiores y exteriores, pantalla de proyección portátil y plegable 4K',
        offer: '48.962',
        price: '87.491',
        img: 'Pantalla 3D de 100 pulgadas 4K.webp',
    },
    {
        title: 'Polvo dental blanqueador hipoalergénico Bubchen 5D White de 80 ml - Limpieza profunda con esencia de perla - Cuidado dental para el aliento fresco, no requiere batería, regalo ideal para mujeres.',
        offer: '16.903',
        price: '33.376',
        img: 'Polvo dental blanqueador hipoa.webp',
    },
    {
        title: 'Auriculares inalámbricos TWS, auriculares estéreo HiFi 9D, auriculares deportivos, auriculares con cancelación de ruido en la oreja con compartimento de carga con pantalla LED',
        offer: '11.369',
        price: '68.611',
        img: 'Auriculares inalámbricos TWS, .webp',
    },
    {
        title: 'KBDFA E88 Drone HD WIFI Helicóptero Cámara HD Altura Sosteniendo RC Plegable Quadcopter Dron Evitación De Obstáculos UAV',
        offer: '134.904',
        price: '362.676',
        img: 'KBDFA E88 Drone HD WIFI Helicó.webp',
    },
    {
        title: 'Juego de llaves combinadas de trinquete de cabeza flexible, llave de acero de 10 mm, juego de herramientas manuales automotrices de engranajes de doble uso, 1 pieza',
        offer: '32.921',
        price: '55.636',
        img: 'Juego de llaves combinadas de .webp',
    },
    {
        title: '1/3/6/9 pzas. Paño mágico de esmeril, esponja desincrustante para limpiar el fondo de las ollas, cepillo de esponja para ollas, esponja para eliminar óxido de hierro, bloque de esponja para lavar platos, almohadillas de fregado, descontaminación potente, suministros de limpieza, herramienta de limpieza, artículos para la vuelta al colegio',
        offer: '4.269',
        price: '9.100',
        img: '1_3_6_9 pzas. Paño mágico de e.webp',
    },
    {
        title: '6pcs/set Reloj De Mujer De Lujo De Cuarzo Con Diamantes De Imitación Brillante Moda Analógica Reloj De Pulsera Y Conjunto De Joyas, Regalo Para Mamá Ella',
        offer: '43.417',
        price: '57.297',
        img: '6pcs_set Reloj De Mujer De Luj.webp',
    },
    {
        title: '1 cepillo Para Aceite, Práctico, Cepillo Con Pelo Para Hornear Para Panqueques, Artículos Del Hogar Resistente A Altas Temperaturas, Cepillo Para Parrilla Que No Se Desprende, Suministros De Cocina.',
        offer: '2.950',
        price: '6.400',
        img: '1 cepillo Para Aceite, Práctic.webp',
    },
    {
        title: 'Peines de limpieza y masaje para mascotas, Peine flotante para eliminar pelos de gato, Cuidado de mascotas, Cepillo de aseo para gatos, Cepillo de vapor eléctrico para mascotas, Masaje de spray eléctrico para gatos y perros, Elimina pelos enredados y sueltos',
        offer: '16.728',
        price: '37.224',
        img: 'Peines de limpieza y masaje pa.webp',
    },
    {
        title: '1pc Círculo Bordado Parche De Tela Para Planchar O Coser Adecuado Para Reparación Y Decoración De Jeans, Chaquetas, Ropa, Bolsas Y Sombreros',
        offer: '6.516',
        price: '11.732',
        img: '1pc Círculo Bordado Parche De .webp',
    },
    {
        title: 'Sandalias deslizantes de EVA transpirables y antiolor con diseño de oso de dibujos animados para hombre, cómodas, antideslizantes, duraderas, con suela suave informal, calzado para hombre.',
        offer: '9.681',
        price: '35.685',
        img: 'Sandalias deslizantes de EVA t.webp',
    },
    {
        title: 'Humidificador de Aromaterapia con Luz Nocturna y Alimentación USB - Perfecto para Dormitorio, Oficina y Ambiente del Coche',
        offer: '11.689',
        price: '19.874',
        img: 'Humidificador de Aromaterapia .webp',
    },
    {
        title: 'Sudadera Con Estampado De Letras, Sudadera Informal De Manga Larga Con Cuello Redondo Para Otoño E Invierno, Ropa De Mujer',
        offer: '22.628',
        price: '83.442',
        img: 'Sudadera Con Estampado De Letr.webp',
    },
    {
        title: 'Mochila De Viaje Con Compartimento Para Zapatos, Bolsa De Equipaje Expandible, Mochila Escolar De Gran Capacidad',
        offer: '123.018',
        price: '220.031',
        img: 'Mochila De Viaje Con Compartim.webp',
    },
    {
        title: '100 piezas de soporte para aretes de silicona, tapones de silicona para aretes, tachuelas para aretes, respaldo de plástico transparente suave de silicona, respaldo de bala para aretes, accesorios de respaldo de pasador de seguridad para aretes',
        offer: '1.604',
        price: '3.780',
        img: '100 piezas de soporte para are.webp',
    },
    {
        title: 'Pantalones largos de mujer, pantalones rectos, largos, sueltos, elegantes, casuales, para salir, con cordón falso, fibra de poliéster (poliéster) con cordón a rayas en la cintura, largos, primavera/otoño sComentario de cotización',
        offer: '30.419',
        price: '81.416',
        img: 'Pantalones largos de mujer, pa.webp',
    },
    {
        title: 'Cámara de doble canal con visión nocturna infrarroja, frontal y interior 1080P, cámara de DVR para coche con pantalla IPS de 8.03 cm, modo de estacionamiento con sensor de movimiento las 24 horas, grabación en bucle (sin tarjeta de 32G)',
        offer: '130.489',
        price: '252.790',
        img: 'Cámara de doble canal con visi.webp',
    },
    {
        title: '5 tapas de paja, adornos de paja y dijes de letras para vasos Stanley de 30 y 40 oz con asa - Accesorios para el día de San Valentín, el día de la madre, la Navidad, el día de acción de gracias y el día de la mujer.',
        offer: '16.482',
        price: '29.168',
        img: '5 tapas de paja, adornos de pa.webp',
    },
    {
        title: '1 Unidad, Taza De Coche De Acero Inoxidable De 20 Oz, Diseño De Impresión De Herramientas De Caja De Herramientas, Taza De Café De Viaje Aislada Al Vacío De Doble Pared Con Tapa, Regalos Para Padres Y Amigos',
        offer: '59.960',
        price: '149.900',
        img: '1 Unidad, Taza De Coche De Ace.webp',
    },
    {
        title: 'Lápiz labial de 3 colores, larga duración, alta reproducción del color, brillo de labios a prueba de agua, bálsamo labial hidratante, lápiz labial, líneas de labios hidratantes y aclarantes, juego de maquillaje para damas, regalos del día de San Valentín, contiene escualano vegetal',
        offer: '5.598',
        price: '12.373',
        img: 'Lápiz labial de 3 colores, lar.webp',
    },
    {
        title: 'Mini Impresora De Fotos Con 11 Rollos De Papel, Impresora Térmica Portátil Para Aplicaciones Android O IOS, Impresora Sin Tinta Para Regalar A Niños, Amigos, Para Uso En Casa, Oficina, Estudio, Impresión De Listas De Trabajo',
        offer: '109.643',
        price: '296.771',
        img: 'Mini Impresora De Fotos Con 11.webp',
    },
    {
        title: 'Conjunto De 2 Piezas De Camiseta Y Pantalones Cortos Con Estampado De Letras Y Bloques De Color, Moderno Y Cómodo Para Niños En Verano',
        offer: '25.094',
        price: '79.508',
        img: 'Conjunto De 2 Piezas De Camise.webp',
    },
    {
        title: 'Cámara de Seguridad HD 1080P para Interior/Exterior con Audio Bidireccional, Wi-Fi, Pan/Tilt/Zoom, Seguimiento de Movimiento - Perfecta para Bebés y Mascotas, Visión Nocturna a Color',
        offer: '58.716',
        price: '146.221',
        img: 'Cámara de Seguridad HD 1080P p.webp',
    },
    {
        title: 'Bolsa de Almuerzo Minimalista y Elegante de Tela Oxford - Ligera, con Cremallera, Bolso Bento para Mujeres | Uso Diario Versátil',
        offer: '9.908',
        price: '24.800',
        img: 'Bolsa de Almuerzo Minimalista .webp',
    },
    {
        title: 'Top corto de punto de tirantes para el Día de San Valentín, top casual sin mangas versátil para primavera y verano, ropa de mujer',
        offer: '13.971',
        price: '38.498',
        img: 'Top corto de punto de tirantes.webp',
    },
    {
        title: 'F524 Altavoz inalámbrico, Subwoofer de doble canal con sonido envolvente para el hogar, viajes, etc',
        offer: '55.498',
        price: '159.997',
        img: 'F524 Altavoz inalámbrico, Subw.webp',
    },
    {
        title: '10/30/50 Piezas Accesorios para el Cabello de Niñas Lindos Dibujos Animados Toalla Anillo Cuerda para el Cabello Anillo para el Cabello',
        offer: '4.798',
        price: '8.999',
        img: '10_30_50 Piezas Accesorios par.webp',
    },
    {
        title: 'Conjunto de 3 Relojes de Cuarzo Romanos Elegantes para Mujer - Esfera Redonda a la Moda con Correa de Cuero Sintético, Idea de Regalo Perfecta',
        offer: '21.317',
        price: '69.767',
        img: 'Conjunto de 3 Relojes de Cuarz.webp',
    },
    {
        title: 'Auriculares inalámbricos, auriculares inalámbricos 5.3, 13MM de altavoz, larga duración de la batería, estuche de carga rápida tipo C, auriculares inalámbricos estéreo para iPhone y Android, auriculares intrauriculares para juegos, negocios y deportes con micrófono.',
        offer: '107.713',
        price: '290.845',
        img: 'Auriculares inalámbricos, auri.webp',
    },
    {
        title: '1pc Silla de hamaca al aire libre Silla de columpio de ocio Lienzo sin almohada y cojín Muebles de jardín de ocio Hamacas para interiores y exteriores, Bolsa sellada OPP',
        offer: '97.751',
        price: '134.253',
        img: '1pc Silla de hamaca al aire li.webp',
    },
    {
        title: 'Conjunto de 3 pantalones cortos deportivos para hombre de color liso con bolsillos con cremallera, pantalones cortos con cordón transpirables y cómodos para entrenamiento de verano, fitness y ropa de gimnasio.',
        offer: '82.597',
        price: '197.346',
        img: 'Conjunto de 3 pantalones corto.webp',
    },
    {
        title: 'Tira De LED RGB3535 De 1pc 5v, Con USB Y Control De Tres Teclas, Para Una Luz Decorativa Colorida De Fondo De TV Para La Sala De Estar Y El Ambiente Del Dormitorio',
        offer: '10.722',
        price: '18.172',
        img: 'Tira De LED RGB3535 De 1pc 5v,.webp',
    },
    {
        title: 'Auriculares inalámbricos con cabina transparente: micrófonos estéreo de alta fidelidad, pantalla digital LED, mini auriculares intrauditivos, cancelación activa de ruido, compatible con conexión inalámbrica, batería de polímero de litio, uso para adultos.',
        offer: '13.961',
        price: '52.998',
        img: 'Auriculares inalámbricos con c.webp',
    },
    {
        title: 'Chaqueta rompevientos con capucha sólida de manga larga y cremallera para hombre, versátil y casual, ideal para actividades al aire libre como senderismo y camping',
        offer: '147.109',
        price: '287.066',
        img: 'Chaqueta rompevientos con capu.webp',
    },
];
