export const themes = [
    {
        folder: 'Anniversary Sale',
        special_name: 'Anniversary Sale',
        special_color: '#E9A800',
        special_color2: '#C89000',
    },
    {
        folder: 'Autumn Savings',
        special_name: 'Autumn Savings',
        special_color: '#874807',
        special_color2: '#6D3B08',
    },
    {
        folder: 'Autumn Savings 2',
        special_name: 'Autumn Savings',
        special_color: '#781E00',
        special_color2: '#5A1500',
    },
    {
        folder: 'Autumn Savings big',
        special_name: 'Autumn Savings big',
        special_color: '#781E00',
        special_color2: '#5A1500',
    },
    {
        folder: 'Autumn Savings big 2',
        special_name: 'Autumn Savings big',
        special_color: '#781E00',
        special_color2: '#5A1500',
    },
    {
        folder: 'Autumn Selections',
        special_name: 'Autumn Selections',
        special_color: '#781E00',
        special_color2: '#5A1500',
    },
    {
        folder: 'Early Autumn',
        special_name: 'Early Autumn',
        special_color: '#874807',
        special_color2: '#6D3B08',
    },
    {
        folder: 'Early Autumn Deals',
        special_name: 'Early Autumn Deals',
        special_color: '#874807',
        special_color2: '#6D3B08',
    },
    {
        folder: 'Early Autumn Offers',
        special_name: 'Early Autumn Offers',
        special_color: '#874807',
        special_color2: '#6D3B08',
    },
    {
        folder: 'Early Autumn Savings',
        special_name: 'Early Autumn Savings',
        special_color: '#874807',
        special_color2: '#6D3B08',
    },
    {
        folder: 'Early Spring Offers',
        special_name: 'Early Spring Offers',
        special_color: '#007ECC',
        special_color2: '#006DB0',
    },
    {
        folder: 'Fall into Savings',
        special_name: 'Fall into Savings',
        special_color: '#B3610B',
        special_color2: '#9E5203',
    },
    {
        folder: 'japon',
        special_name: '秋のプロモーション',
        special_color: '#781E00',
        special_color2: '#5A1500',
    },
    {
        folder: 'NATIONAL DAY',
        special_name: 'NATIONAL DAY',
        special_color: '#008C8B',
        special_color2: '#006E6E',
    },
    {
        folder: 'New Season Offers',
        special_name: 'New Season Offers',
        special_color: '#007ECC',
        special_color2: '#006DB0',
    },
    {
        folder: 'Ofertas de Inicio de Otoño',
        special_name: 'Ofertas de Inicio de Otoño',
        special_color: '#874807',
        special_color2: '#6D3B08',
    },
    {
        folder: 'OFERTAS DE PRIMAVERA',
        special_name: 'OFERTAS DE PRIMAVERA',
        special_color: '#30A352',
        special_color2: '#219242',
    },
    {
        folder: 'Opening SALE',
        special_name: 'Opening SALE',
        special_color: '#BA0700',
        special_color2: '#960601',
    },
    {
        folder: 'PAYDAY SALE',
        special_name: 'PAYDAY SALE',
        special_color: '#E32F0B',
        special_color2: '#BF2001',
    },
    {
        folder: 'PREBAJAS DE VERANO',
        special_name: 'PREBAJAS DE VERANO',
        special_color: '#008FCD',
        special_color2: '#007EB5',
    },
    {
        folder: 'Primavera de Ofertas',
        special_name: 'Primavera de Ofertas',
        special_color: '#007ECC',
        special_color2: '#006DB0',
    },
    {
        folder: 'Promocion de Otoño',
        special_name: 'Promoción de Otoño',
        special_color: '#B3610B',
        special_color2: '#9E5203',
    },
    {
        folder: 'Promocion de Otoño 2',
        special_name: 'Promoción de Otoño',
        special_color: '#874807',
        special_color2: '#6D3B08',
    },
    {
        folder: 'Promocion de Otoño 3',
        special_name: 'Promoción de Otoño',
        special_color: '#781E00',
        special_color2: '#5A1500',
    },
    {
        folder: 'REBAJAS DE TEMPORADA',
        special_name: 'REBAJAS DE TEMPORADA',
        special_color: '#DB3E43',
        special_color2: '#CC2C31',
    },
    {
        folder: 'Rosh Hashana Sale',
        special_name: 'Rosh Hashana Sale',
        special_color: '#A55201',
        special_color2: '#8E4600',
    },
    {
        folder: 'Spring Deals',
        special_name: 'Spring Deals',
        special_color: '#007ECC',
        special_color2: '#006DB0',
    },
    {
        folder: 'Amor y Amistad',
        special_name: 'Amor y Amistad',
        special_color: '#f9697f',
        special_color2: '#eb495e',
    },
];
